// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuufuewpbgciitslfvbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dWZ1ZXdwYmdjaWl0c2xmdmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjU5NTAsImV4cCI6MjA2NTc0MTk1MH0.PcVsA7NtWSVza9ZsKURMv7yRTCqWofk734R2eILgwh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});